name: android2

on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'android/**'
      - '.github/workflows/android2.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext openjdk-11-jdk-headless
    - name: Build with Gradle
      run: cd android; ./gradlew assembleDebug
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minetest-armeabi-v7a.apk
        path: android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minetest-arm64-v8a.apk
        path: android/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
    - name: Save x86 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minetest-x86.apk
        path: android/app/build/outputs/apk/debug/app-x86-debug.apk
    - name: Save x86_64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Minetest-x86_64.apk
        path: android/app/build/outputs/apk/debug/app-x86_64-debug.apk
