name: MSYS2

on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/buildbot/**'
      - 'misc/*.manifest'
      - '.github/workflows/msys2_build.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'util/buildbot/**'
      - 'misc/*.manifest'
      - '.github/workflows/msys2_build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        release: false

    - name: Update environment
      shell: msys2 {0}
      run: |
        pacman -Syu --noconfirm

    - name: Install dependencies
      shell: msys2 {0}
      run: |
        pacman -S git mingw-w64-clang-x86_64-{clang,cmake,ninja,curl-winssl,libpng,libjpeg-turbo,freetype,libogg,libvorbis,sqlite3,openal,zstd,gettext,luajit,SDL2} --noconfirm
    
    - name: Compile
      shell: msys2 {0}
      run: |
        git clone --depth 1 https://github.com/minetest/minetest
        cd minetest
        mkdir build
        cd build
        cmake .. -G Ninja
        ninja

    - name: Bundle DLLs
      shell: msys2 {0}
      run: |
        curl https://raw.githubusercontent.com/rollerozxa/msys2-bundledlls/master/bundledlls > ../bundledlls
        ../bundledlls ../bin/minetest.exe ../bin/

    - name: Zip the artifact
      shell: bash
      run: |
        cd minetest
        7z a minetest.zip ./*
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: minetest_MSYS2_windows
        path: minetest/minetest.zip
